### PR TITLE
Change `console.setEndpoint()` to `fastly.getLogger()`

### PR DESCRIPTION
**Pull request by smaeda-ks**
https://js-compute-reference-docs.edgecompute.app/interfaces/fastly.html#getlogger

https://js-compute-reference-docs.edgecompute.app/interfaces/logger.html

I'll make a separate PR to update: https://developer.fastly.com/learning/compute/javascript/#logging

### CODE REVIEW

**Comment by tschneidereit** [comment]
Thank you for this, good catch!

I now wonder if we shouldn't just remove this entire paragraph, though: neither the Rust nor AssemblyScript starter kits have this kind of explanation in them, either. Would you be up for changing the PR to remove the "NOTE" paragraph?

**Comment by smaeda-ks** [comment]
@tschneidereit ok, so literally no logging example included in this file?

**Comment by tschneidereit** [comment]
> @tschneidereit ok, so literally no logging example included in this file?

@smaeda-ks we don't have any in the other starter kits, so that seems ok to me?

**Comment by smaeda-ks** [comment]
Thanks, @tschneidereit. As a frontline support engineer, I may have a different view. The logging part is one of the most frequently asked questions and this sort of information is still worth leaving there from the developer experience point of view. Especially given it requires our custom module in that way, this would save their time, I believe.

**Comment by smaeda-ks** [comment]
Removed the NOTE and added a link to the updated DevHub page instead.

**Review by tschneidereit — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
