### PR TITLE
replace webpack with esbuild

### PR DESCRIPTION
**Pull request by vtenfys**
This PR replaces Webpack with esbuild, to reduce dependencies and increase build performance.

From [the website of esbuild](https://esbuild.github.io/):

> Our current build tools for the web are 10-100x slower than they could be. The main goal of the esbuild bundler project is to bring about a new era of build tool performance, and create an easy-to-use modern bundler along the way.

In benchmarks, esbuild is 125x faster than Webpack at producing a production bundle of 10 copies of the Three.js library.

### CODE REVIEW

**Comment by torch2424** [comment]
@valerie-makes Hello! First, thank you very much for opening a PR! I'm glad to see your interest in the JS SDK for C@E! 😄 

I appreciate the info on esbuild, it's definitely something I have been watching myself, and I have a few friends in the open source scene that are big fans of esbuild! 😄 

However, I was curious why you wanted to introduce esbuild to this project in particular?

We had chose webpack originally, since we figured it'd be a bundler that most JavaScript developers would be familiar with already, but also to my knowledge, webpack has a [unique way of shimming and polyfilling JS code in multiple module formats](https://webpack.js.org/guides/shimming/), and tends to really excel when you need to pull in JS code that was written for many different formas together (e.g getting a Node JS package to play nice with a browser JS package). And since our C@E JS Compute runtime isn't Node, and isn't technically a standard browser environment, this becomes quite important for allowing users to use some of their favorite npm packages. 🤔 

Usually, for big changes like this I think we'd prefer to chat about it first before writing code. However, we're already here, and I'd still be happy to hear your thoughts! 😄  And in the meantime, if you see the needs for faster builds for your JS C@E project, I'd say totally go for it if it's working well for you and your team! 😄 

Thanks! Let me know what you think! 🎉

**Comment by valenfys** [comment]
Thank you for your thoughtful message! I'll try to address each of your points.

> I was curious why you wanted to introduce esbuild to this project in particular?

I believe in choosing good defaults for templates with the potential for a large userbase. Webpack is very popular and highly configurable, but with the rise of projects like esbuild and swcpack offering much better performance and easier-to-use APIs (albeit with less configurability), I believe that over time it is becoming less popular in modern JS tooling.

esbuild has also gained adoption in a number of high-profile projects, including the web framework Remix, and the build tools Vite and Snowpack.

This isn't to say that Webpack is not "good" or that it isn't a sensible choice for reliability, but given the newness and beta status of JavaScript on C@E, I believe it could be the right kind of project to explore more modern tooling without much to lose, along with the benefit of improved build performance (and therefore a positive environmental impact).

> webpack has a unique way of shimming and polyfilling JS code in multiple module formats, and tends to really excel when you need to pull in JS code that was written for many different formas together (e.g getting a Node JS package to play nice with a browser JS package). And since our C@E JS Compute runtime isn't Node, and isn't technically a standard browser environment, this becomes quite important for allowing users to use some of their favorite npm packages. 🤔

On the point of different formats, and 3rd-party NPM packages:

esbuild doesn't officially support Web Workers, but [the `platform` option is set to `browser` by default](https://esbuild.github.io/api/#platform). For this platform, the [output format](https://esbuild.github.io/api/#format) is set to IIFE which is compatible with Web Workers, and the [main fields](https://esbuild.github.io/api/#main-fields) setting is configured to prefer browser variants of NPM packages. Although it isn't explicitly stated, CommonJS packages are also supported:

> Because [the `main` field of `package.json` is] intended for use with node, it's reasonable to expect that the file path in this field is a CommonJS-style module. ([source](https://esbuild.github.io/api/#main-fields))

This can be confirmed by following the instructions in [Your first bundle](https://esbuild.github.io/getting-started/#your-first-bundle) which makes use of the package React, which is only distributed in CommonJS format.

On the point of polyfills and shimming:

I believe the [`inject` option](https://esbuild.github.io/api/#inject) is esbuild's equivalent of Webpack's `ProvidePlugin`. I noticed that the current Webpack config has a polyfill for the `URL` interface, but I didn't reimplement this with esbuild - my understanding is that Node.js and the Compute@Edge platform both already support this API, so a polyfill is unnecessary.

> Usually, for big changes like this I think we'd prefer to chat about it first before writing code. However, we're already here, and I'd still be happy to hear your thoughts! 😄 And in the meantime, if you see the needs for faster builds for your JS C@E project, I'd say totally go for it if it's working well for you and your team! 😄

Admittedly, I'm rather eager when it comes to writing code before discussing ideas 😅 I also figured it would be worth opening the PR to get some thoughts, since it didn't take me much time implementing these changes.

Right now I'm not using C@E for any production projects but I've been exploring it among other platforms - right now I'm working solo on some freelance projects (mostly using Vercel for hosting and CDN), and I've been particularly interested in comparing the developer experience of CloudFlare Workers and Fastly Compute@Edge.

As a final note, I understand if this PR isn't accepted, since it was quite spontaneous and I'm aware that Webpack is the more mature platform of the two :) As they say, if it ain't broke, don't fix it!

**Comment by torch2424** [comment]
> Thank you for your thoughtful message! I'll try to address each of your points.

You are welcome! 😄 I'll go ahead and do the same! 😄 

> I believe in choosing good defaults for templates with the potential for a large userbase. Webpack is very popular and highly configurable, but with the rise of projects like esbuild and swcpack offering much better performance and easier-to-use APIs (albeit with less configurability), I believe that over time it is becoming less popular in modern JS tooling. esbuild has also gained adoption in a number of high-profile projects, including the web framework Remix, and the build tools Vite and Snowpack. This isn't to say that Webpack is not "good" or that it isn't a sensible choice for reliability, but given the newness and beta status of JavaScript on C@E, I believe it could be the right kind of project to explore more modern tooling without much to lose, along with the benefit of improved build performance (and therefore a positive environmental impact). 

Definitely! 😄 100% We are definitely thinking of our technology choices with our userbase in mind. I agree that Webpack maybe doesn't have the best developer experience compared to more modern build tools. And the more recent build tools are showing huge performance increases. 😄 

However, the modern JS build tools like esbuild are still relatively very new, and they are becoming popular amongst many developers who follow open source JS closely and things. But not as much across the industry. 🤔  To show this we can take a look at the State of JS survey results from 2020 (2021 is currently happening, so these are the latest results as of me writing this): https://2020.stateofjs.com/en-US/technologies/build-tools/ 

If you click the "Satisfaction | Interest | Usage | Awareness" buttons. You will see that developers do tend to be more satisfied with esbuild, but Webpack is definitely the leader when it comes to Usage and Awareness (and by a very wide margin when compared to other tools). 😄 In my opinion (I can bring in other team opinions as well), our goal as an SDK, is to provide functionality to tools our prospective userbase already uses, or already knows. Thus, I think Webpack still makes the most sense here, backed by data (it's a survey, so maybe not 100% the best data, but better than guessing for sure! 😅 ).

I am happy to hear that other high-profile JS projects have chosen more modern tools for their defaults. And I totally think that makes sense for them! 😄 

I also appreciate the positive environmental impact these more modern build tools are bringing about to the industry! Using more modern JavaScript tooling and code is something we could definitely encourage to our users in documentation and things! 😄 

> On the point of different formats, and 3rd-party NPM packages: esbuild doesn't officially support Web Workers, but the platform option is set to browser by default. For this platform, the output format is set to IIFE which is compatible with Web Workers, and the main fields setting is configured to prefer browser variants of NPM packages. Although it isn't explicitly stated, CommonJS packages are also supported: This can be confirmed by following the instructions in Your first bundle which makes use of the package React, which is only distributed in CommonJS format.On the point of polyfills and shimming: I believe the inject option is esbuild's equivalent of Webpack's ProvidePlugin. I noticed that the current Webpack config has a polyfill for the URL interface, but I didn't reimplement this with esbuild - my understanding is that Node.js and the Compute@Edge platform both already support this API, so a polyfill is unnecessary.

I'm bundling these two comments together, because I think they are related, and I can address with some extra context 😄 

So, Javascript on C@E runs a WebAssembly compiled SpiderMonkey (the JS engine that runs in Firefox). You can find that project here: https://github.com/fastly/js-compute-runtime

Because the Wasm  / WASI version of Spidermonkey is super new (like, if I'm not mistaken we figured it out specifically for C@E), it's not necessarily a 1:1 implementation of Spidermonkey that you'd maybe use in your day to day. Some things are missing, and this is because WebAssembly and WASI are still being developed on, and various teams across the industry are working on the specification to enable new features. 😄 

So, yes, totally compiling some simple Javascript to an IIFE would 100% work on our spidermonkey. But, things get funny when you start importing packages that expect certain node globals, or browser globals that packages will assume they have when they are transpiled into their respective module formats (CommonJS for node, ES Module for browser, etc...).  Essentially you usually want to try and find Universal JavaScript packages where you can, because they have the highest likelihood of working. 🤔 

With this being said, it's worth noting, because our Wasm compiled Spidermonkey has these limitations around it's globals, and what's available to us in the Wasm  / WASI standard, we had to add the URL polyfill. And we can't really compare our current C@E implementation to a Node or a browser environment, it's it's own thing really, that takes a lot of bits and pieces from each. but it's not 1:1 to either of them 😅 

> Admittedly, I'm rather eager when it comes to writing code before discussing ideas sweat_smile I also figured it would be worth opening the PR to get some thoughts, since it didn't take me much time implementing these changes.

Haha! No worries at all! 😄 I only bring it up, because if we wanted to merge this, it would be a really large discussion amongst our team, weighing the pros and cons, and we'd have to communicate it to customers, etc... And glad to hear that the changes didn't take too long to implement! 😄 

> Right now I'm not using C@E for any production projects but I've been exploring it among other platforms - right now I'm working solo on some freelance projects (mostly using Vercel for hosting and CDN), and I've been particularly interested in comparing the developer experience of CloudFlare Workers and Fastly Compute@Edge.

Ah! I'd be stoked to hear any feedback you have any! if you happened to take notes or anything, please send them over! I can go ahead and share it with the Devex and Devrel team 😄  And all in all, that's cool that you are working on those things, thanks for trying C@E! 😄 

> As a final note, I understand if this PR isn't accepted, since it was quite spontaneous and I'm aware that Webpack is the more mature platform of the two :) As they say, if it ain't broke, don't fix it!

Totally! Glad to hear there won't be any hard feelings 😅 As of right now, I think we'll most likely stick with Webpack. But, if we hear more of a desire from esbuild from our community at large, I'm sure we'd be happy to look into merging something like this in the future! 😄

**Comment by donferi** [comment]
Love the detailed conversation going on in there. I would like to chime in since I'm also comparing Compute@Edge vs some competitors for a few new projects at work.

One benefit I see of using esbuild is their built-in typescript support. Right now with this starter kit I need to manually setup babel and use it via webpack, while with esbuild it just works.

From the same link provided above: https://2020.stateofjs.com/en-US/technologies/javascript-flavors/ typescript is rapidly growing in terms of usage.

**Comment by Integralist** [comment]
👋🏻 

Thanks @torch2424 for these excellent clarifying details. 

Just to add that this doesn't stop anyone from making changes to the starter kit to use esbuild (as @valerie-makes has obviously already done).  If these sorts of changes are something you're doing on a regular basis (that's the impression I got from @donferi), then by all means fork the public repo and make the changes you need and then you can use the [Fastly CLI'](https://github.com/fastly/cli)s `--from` flag to download your fork's version of the starter kit...

Screenshot 2022-01-20 at 09 36 58

> **NOTE**: Be sure to use your fork's SSH endpoint, not HTTPS.

**Comment by Integralist** [comment]
Because it seems this discussion has reached a conclusion...

> Glad to hear there won't be any hard feelings 😅 As of right now, I think we'll most likely stick with Webpack. But, if we hear more of a desire from esbuild from our community at large, I'm sure we'd be happy to look into merging something like this in the future! 😄

...I'm going to close this issue now. 

But do please continue to discuss, or reopen the issue, if necessary.

**Pull request closed without merging**
